COLLISSION_DEBUG = false

STORAGE_DIFFICULTY = 10
STORAGE_MUSIC = 11
STORAGE_SFX = 12

STORAGE_HIGH_SCORES_LAST_NAME = 39
STORAGE_HIGH_SCORES_START = 40 -- 30 places, up to 59

STORAGE_ALREADY_PLAYED = 63
